name: customNature
main: main.Main
version: 0.0.1-SNAPSHOT


commands:
    cnat:
        description: Spawns a custom item
        usage: /cnat
        aliases: [cn]
        permission: customNature.spawnItem
        permission-message: You need the customNature.spawnItem permission to execute this command
    cncustom:
        description: Opens the customization menu
        usage: /cncustom
        aliases: [cnc]
        permission: customNature.custom
        permission-message: You need the customNature.custom permission to execute this command